#!/usr//bin/env bash
# Transfers a file from our client to a server
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#   if less than 3 parameters passed

if [ "$#" -lt 3 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]
then
    scp -q -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    scp -q "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
