#!/usr/bin/env bash
# Set up and configure an Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 80
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen \[::\]:80 default_server;/a \\n\trewrite ^/redirect_me / permanent;' /etc/nginx/sites-available/default
service nginx restart
