#!/usr/bin/env bash
# Set up and configure an Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 80
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen \[::\]:80 default_server;/a \\n\trewrite ^/redirect_me / permanent;\n\terror_page 404 \/404.html;' /etc/nginx/sites-available/default
service nginx start