#!/usr/bin/env bash
# Configure Nginx like the 2696-web-01 and add dynamically a custom HTTP header with the pair key: value
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
service nginx start

