#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and at the 9th iteration
# displays Holberton School and then Hi on a new line
counter=0
while [ $counter -le 9 ]
do
  echo "Holberton School"
  ((counter++))
  if [ $counter == 9 ]
  then
        echo "Hi"
  fi
done
