#!/usr/bin/env bash
# Displays numbers from 1 to 20 with some print conditions
count=0
while ((count++ < 20 ))
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
done
