#!/usr/bin/env bash
# Script that give info about the holbertonschool file
file='holbertonschool'
if [ -e "$file" ]
then
	echo $file' file exists'
    if [ -f "$file" ]
    then
        if [ -s "$file" ]
        then
            echo $file' is not empty'
        else
            echo $file' is empty'
        fi
        echo $file' is a regular file'    
    fi
else
	echo $file' file does not exist'
fi
