#!/usr/bin/env bash
# Fix the container
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
pkill apache2
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf | sudo -u nginx service nginx restart
